name: Publish Python distribution to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: Somerandomguy10111/devops/actions/basepy@main
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    - name: Build
      run: |
        python -m build
    - name: Publish
      run: |
        twine upload dist/* --repository pypi
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_KEY }}
