name: Publish Python distribution to PyPI

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest
    permissions:
      id-token: write
    
    steps:
    - name: Prepare python + code
      uses: Somerandomguy10111/devops/actions/basepy@main
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc
      with:
        user: __token__
        password: ${{ secrets.HOLYTOOLS_PYPI_API_TOKEN }}